#!/bin/sh

#	MOVE TO .git/hooks to take effect

# An example hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>
#
# This sample shows how to prevent push of commits where the log message starts
# with "WIP" (work in progress).

local_branch_name="$(git rev-parse --abbrev-ref HEAD)"

echo "Push hook. Check if pushing from development branch"
echo "Current branch: "$local_branch_name

if [[ $local_branch_name = "development" ]]
then
	echo "Good"
	exit 0
else
	echo "Not on development. Push forbidden"
	exit 1
fi